"""create psychology_reports table

Revision ID: 668b6dfaf0aa
Revises: e8eefd8ade70
Create Date: 2026-09-20 14:38:23.895173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '668b6dfaf0aa'
down_revision: Union[str, Sequence[str], None] = 'e8eefd8ade70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psychology_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_job_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('agent_type', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('market_temperature', sa.Integer(), nullable=False),
    sa.Column('expectation_gap', sa.Text(), nullable=False),
    sa.Column('fear_of_loss', sa.Float(), nullable=False),
    sa.Column('fomo', sa.Float(), nullable=False),
    sa.Column('narrative_saturation', sa.Float(), nullable=False),
    sa.Column('crowding', sa.Float(), nullable=False),
    sa.Column('dominant_narrative', sa.Text(), nullable=False),
    sa.Column('differentiated_or_contrarian_view', sa.Text(), nullable=False),
    sa.Column('psychology_confidence', sa.Float(), nullable=False),
    sa.Column('previous_state_id', sa.UUID(), nullable=True),
    sa.Column('evidence', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.ForeignKeyConstraint(['previous_state_id'], ['psychology_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psychology_reports_research_job_id'), 'psychology_reports', ['research_job_id'], unique=False)
    op.create_index(op.f('ix_psychology_reports_ticker'), 'psychology_reports', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_psychology_reports_ticker'), table_name='psychology_reports')
    op.drop_index(op.f('ix_psychology_reports_research_job_id'), table_name='psychology_reports')
    op.drop_table('psychology_reports')
    # ### end Alembic commands ###
