"""add portfolio concentration fields to risk_assessments

Revision ID: 72e71df0d027
Revises: b56b2ad5b5bb
Create Date: 2026-09-21 20:27:38.480841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e71df0d027'
down_revision: Union[str, Sequence[str], None] = 'b56b2ad5b5bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_assessments', sa.Column('existing_position_pct', sa.Float(), nullable=True))
    op.add_column('risk_assessments', sa.Column('portfolio_max_position_pct_cap', sa.Float(), server_default='10.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_assessments', 'portfolio_max_position_pct_cap')
    op.drop_column('risk_assessments', 'existing_position_pct')
    # ### end Alembic commands ###
