"""create red_team_reports table

Revision ID: 75c8c64638c4
Revises: 668b6dfaf0aa
Create Date: 2026-09-20 14:49:21.295127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75c8c64638c4'
down_revision: Union[str, Sequence[str], None] = '668b6dfaf0aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('red_team_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_job_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('agent_type', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('independent_bear_case', sa.Text(), nullable=False),
    sa.Column('key_risks', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('thesis_challenges', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('weakest_point_in_thesis', sa.Text(), nullable=False),
    sa.Column('what_would_invalidate_the_bear_case', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_red_team_reports_research_job_id'), 'red_team_reports', ['research_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_red_team_reports_research_job_id'), table_name='red_team_reports')
    op.drop_table('red_team_reports')
    # ### end Alembic commands ###
