"""create risk_assessments table

Revision ID: 7935b20bf9a3
Revises: fb657d9386de
Create Date: 2026-09-20 15:33:42.393612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7935b20bf9a3'
down_revision: Union[str, Sequence[str], None] = 'fb657d9386de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_job_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('annualized_volatility', sa.Float(), nullable=False),
    sa.Column('suggested_position_size_pct', sa.Float(), nullable=False),
    sa.Column('stop_loss_distance_pct', sa.Float(), nullable=False),
    sa.Column('max_position_pct_cap', sa.Float(), nullable=False),
    sa.Column('target_position_volatility_contribution_pct', sa.Float(), nullable=False),
    sa.Column('notes', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_research_job_id'), 'risk_assessments', ['research_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_assessments_research_job_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    # ### end Alembic commands ###
