"""create trade_proposals table

Revision ID: 8a0ac66f2482
Revises: 7935b20bf9a3
Create Date: 2026-09-20 15:36:13.326423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a0ac66f2482'
down_revision: Union[str, Sequence[str], None] = '7935b20bf9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_job_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('catalyst', sa.Text(), nullable=False),
    sa.Column('expectation_gap', sa.Text(), nullable=False),
    sa.Column('risk_notes', sa.Text(), nullable=False),
    sa.Column('invalidation_conditions', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('uncertainties', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('entry_price_range', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('position_size_pct', sa.Float(), nullable=True),
    sa.Column('stop_loss_distance_pct', sa.Float(), nullable=True),
    sa.Column('fundamental_report_id', sa.UUID(), nullable=True),
    sa.Column('psychology_report_id', sa.UUID(), nullable=True),
    sa.Column('red_team_report_id', sa.UUID(), nullable=True),
    sa.Column('quant_metrics_id', sa.UUID(), nullable=True),
    sa.Column('risk_assessment_id', sa.UUID(), nullable=True),
    sa.Column('evidence', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_proposals_research_job_id'), 'trade_proposals', ['research_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_proposals_research_job_id'), table_name='trade_proposals')
    op.drop_table('trade_proposals')
    # ### end Alembic commands ###
