"""create human_decisions table

Revision ID: 9c73bcfc56d4
Revises: 8a0ac66f2482
Create Date: 2026-09-20 15:46:16.402120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c73bcfc56d4'
down_revision: Union[str, Sequence[str], None] = '8a0ac66f2482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_job_id', sa.UUID(), nullable=False),
    sa.Column('trade_proposal_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_decisions_research_job_id'), 'human_decisions', ['research_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_human_decisions_research_job_id'), table_name='human_decisions')
    op.drop_table('human_decisions')
    # ### end Alembic commands ###
