"""create shadow_positions table

Revision ID: b56b2ad5b5bb
Revises: 9c73bcfc56d4
Create Date: 2026-09-20 16:26:45.577225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b56b2ad5b5bb'
down_revision: Union[str, Sequence[str], None] = '9c73bcfc56d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shadow_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_job_id', sa.UUID(), nullable=False),
    sa.Column('trade_proposal_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('entry_price_as_of', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_proposal_id')
    )
    op.create_index(op.f('ix_shadow_positions_research_job_id'), 'shadow_positions', ['research_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shadow_positions_research_job_id'), table_name='shadow_positions')
    op.drop_table('shadow_positions')
    # ### end Alembic commands ###
