"""create evidence table

Revision ID: def7447f0a8a
Revises: a5fc55089ec4
Create Date: 2026-09-18 10:19:28.282243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'def7447f0a8a'
down_revision: Union[str, Sequence[str], None] = 'a5fc55089ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'source_url', name='uq_evidence_ticker_source_url')
    )
    op.create_index(op.f('ix_evidence_ticker'), 'evidence', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_ticker'), table_name='evidence')
    op.drop_table('evidence')
    # ### end Alembic commands ###
