"""create fundamental_reports table

Revision ID: e8eefd8ade70
Revises: def7447f0a8a
Create Date: 2026-09-20 14:17:32.313027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8eefd8ade70'
down_revision: Union[str, Sequence[str], None] = 'def7447f0a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundamental_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_job_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('agent_type', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_findings', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('financial_health', sa.Text(), nullable=False),
    sa.Column('valuation_view', sa.Text(), nullable=False),
    sa.Column('catalysts', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('risks', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fundamental_reports_research_job_id'), 'fundamental_reports', ['research_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fundamental_reports_research_job_id'), table_name='fundamental_reports')
    op.drop_table('fundamental_reports')
    # ### end Alembic commands ###
