"""create quant_metrics table

Revision ID: fb657d9386de
Revises: 75c8c64638c4
Create Date: 2026-09-20 15:10:34.234526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb657d9386de'
down_revision: Union[str, Sequence[str], None] = '75c8c64638c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quant_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_job_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('benchmark_ticker', sa.String(length=16), nullable=False),
    sa.Column('sector_ticker', sa.String(length=16), nullable=True),
    sa.Column('lookback_trading_days', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cumulative_return', sa.Float(), nullable=False),
    sa.Column('annualized_volatility', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('correlation_to_benchmark', sa.Float(), nullable=False),
    sa.Column('max_drawdown', sa.Float(), nullable=False),
    sa.Column('cumulative_abnormal_return', sa.Float(), nullable=False),
    sa.Column('average_daily_volume', sa.Float(), nullable=False),
    sa.Column('sector_relative_return', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quant_metrics_research_job_id'), 'quant_metrics', ['research_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quant_metrics_research_job_id'), table_name='quant_metrics')
    op.drop_table('quant_metrics')
    # ### end Alembic commands ###
